function img1 = flo_imtranslate(img2, flow)
[x, y] = meshgrid(1:size(img2,2), 1:size(img2,1));
img1 = cat(3,...
    uint8(interp2(double(img2(:,:,1)), x-flow(:,:,1), y-flow(:,:,2))),...
    uint8(interp2(double(img2(:,:,2)), x-flow(:,:,1), y-flow(:,:,2))),...
    uint8(interp2(double(img2(:,:,3)), x-flow(:,:,1), y-flow(:,:,2))));